name: ICR Image build and push

on:
  push:
    branches: [ "main" ]
    # When tested that it works, put restrictions on the paths
    # paths: ['containers/**']

env:
  MAIN_IMAGE_NAME: sch-bm-deploy
  CLEAN_IMAGE_NAME: sch-bm-clean
  REGISTRY_URL: us.icr.io
  ICR_NAMESPACE: rolling-iaas
  ICR_TOKEN: ${{secrets.ICR_TOKEN}}

jobs:
  build-and-push-main-job-image:
    name: Build main job image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: list current directory contents
      id: list
      run: pwd && ls -la 
    - name: Build container image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.ICR_NAMESPACE  }}/${{ env.MAIN_IMAGE_NAME }}
        tags: latest ${{ steps.date.outputs.date }}
        context: ./containers/main-job
        containerfiles: |
          ./containers/main-job/Dockerfile
  #   - name: Push To ICR
  #     id: push-to-icr
  #     uses: redhat-actions/push-to-registry@v2
  #     with:
  #       image: ${{ steps.build-image.outputs.image }}
  #       tags: ${{ steps.build-image.outputs.tags }}
  #       username: iamapikey
  #       password: ${{ env.ICR_TOKEN }}
  #       registry: ${{ env.REGISTRY_URL }}

  #   - name: Print image url
  #     run: echo "Image pushed to ${{ steps.push-to-icr.outputs.registry-paths }}"
  
  # build-and-push-clean-job-image:
  #   name: Build clean up job image
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: containers/clean-up

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Get current date
  #     id: date
  #     run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
  #   - name: Buildah Action
  #     id: build-image
  #     uses: redhat-actions/buildah-build@v2
  #     with:
  #       image: ${{ env.ICR_NAMESPACE  }}/${{ env.CLEAN_IMAGE_NAME }}
  #       tags: latest ${{ steps.date.outputs.date }}
  #       containerfiles: |
  #         ./Dockerfile
  #   - name: Push To ICR
  #     id: push-to-icr
  #     uses: redhat-actions/push-to-registry@v2
  #     with:
  #       image: ${{ steps.build-image.outputs.image }}
  #       tags: ${{ steps.build-image.outputs.tags }}
  #       username: iamapikey
  #       password: ${{ env.ICR_TOKEN }}
  #       registry: ${{ env.REGISTRY_URL }}

  #   - name: Print image url
  #     run: echo "Image pushed to ${{ steps.push-to-icr.outputs.registry-paths }}"